### ISSUE TITLE
Unnecessary fields in docker compose files

### ISSUE THREAD

**Issue by Jean-Eudes-le-retour** [cyberbotics/webots-server#21]
I recently did some tests and it seems that some fields inside the docker compose files are unnecessary: `privileged`, everything concerning `XAUTHORITY` and `QT_X11_NO_MITSHM`

Does anybody know why they were set in the first place?

Additionally, it seems that Intel graphics cards (not our case) need an additional volume to be shared with the host to be able to use the GPU: `/dev/dri`

**Comment by omichel** [comment]
I have no idea about this. I would say that we should remove whatever is useless.

**Comment by Jean-Eudes-le-retour** [comment]
Apparently the `XAUTHORITY` related field are there to be able to see Webots' GUI from an SSH connection (implemented in part in [simulation_server.py](https://github.com/cyberbotics/webots/blame/a3dad99f3d25750c3b58dda1ae1d8d92bd756409/resources/web/server/simulation_server.py#L279)) as explained in this [tutorial](https://github.com/cyberbotics/webots-cloud/wiki/Running-Webots-in-a-Docker-container). The problem is that currently this mechanism doesn't work because the Docker containers do not have access to the correct ports to display the GUI (ports 6000 + DISPLAY if I understood `ssh -X`'s  DISPLAY mechanism correctly).

A way of "correcting" this would be to add the equivalent `--net host` from the run command to the docker file with the field `network_mode: host` but that would be a very bad idea security-wise.

Another way would be to change the docker compose files to open the correct port is there is an SSH connection but that doesn't seem easy to do.

Or we could remove all `XAUTHORITY` related fields from the "production" docker compose files and have a separate "debug" docker compose file that would have all of them + the `network_mode: host` field for debugging purposes.

**Comment by omichel** [comment]
Yes, the last option seems to be the best and the simplest to implement. We may simply add a comment in the code explaining how to re-introduce the display of the Webots GUI from a SSH connection.
