### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by jeffhong824** [cyberbotics/webots-server#29]
The issue "Address already in use" occurred while following the protocol-and-quick-start instructions, specifically when running "./server.sh start local."
You can find more information in the link below:
https://cyberbotics.com/doc/guide/protocol-and-quick-start

env
Ubunti 20.04.6 LTS
Kernel Linux 5.4.0-167-generic
Architecture x86-64

![image](https://github.com/cyberbotics/webots-server/assets/61589737/4df061e8-0d4c-4c8f-9d25-286c8dacc539)

**Comment by omichel** [comment]
That's probably because your server is already using the port specified in the configuration file. You should try changing [this port](https://github.com/cyberbotics/webots-server/blob/main/config/session/local.json#L3) or stop the service on your server which uses this port.
